theme: jekyll-theme-slate
title: Levertion's Minecraft Creations
permalink: /:categories/:slug.html
google_analytics_disabled: UA-103575807-1
url: https://levertion.github.io
kramdown:
  toc_levels: 1..2
lang: en_GB
twitter:
  username: levertionmc
