# Dependencies
markdown: kramdown
highlighter: rouge

title: Levertion
tagline: 'Minecraft Creations'
description: A selection of Minecraft creations by <a href="https://twitter.com/LevertionMC">Levertion</a>
permalink: /:categories/:slug/
google_analytics: UA-103575807-1
url: https://levertion.github.io
author:
  name:           'Levertion'
  url:            https://twitter.com/LevertionMC]
github:
  repo: https://github.com/Levertion/levertion.github.io
lang: en_GB
twitter:
  username: levertionmc
social:
  links:
    - https://twitter.com/LevertionMC
    - https://github.com/Levertion
logo: /images/logo.png
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
disqus:
  shortname: levertion
repository: levertion/levertion.github.io
show_drafts: false